### ISSUE TITLE
UI: Implement upload, fetch and paste input methods for data input

### ISSUE THREAD

**Issue by beveradb** [HeriotWattMEng2015/ShExDemo#2]
Multiple data file input methods sought, including drag-and-drop text files, copy-pasting and possibly file fetching with CORS (and accompanied help guide) as an optional task.

**Comment by skhutan** [comment]
drag-and-drop and copy-paste data input implemented, CORS data fetching + help guide to be completed as an optional feature

**Comment by beveradb** [comment]
This issue was moved to HeriotWattMEng2015/ShExValidata#4
