### ISSUE TITLE
Create (find / fix / test) a working ShEx Schema for the HCLS dataset

### ISSUE THREAD

**Issue by beveradb** [HeriotWattMEng2015/ShExDemo#7]
Alasdair's existing (out of date) one can be found here: https://github.com/AlasdairGray/HCLSValidator/blob/master/hcls-validator.shex

HCLS Dataset descriptor to correct against:
http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/

**Comment by Doix** [comment]
I got this.

**Comment by Doix** [comment]
W.I.P version is found here: https://github.com/HeriotWattMEng2015/ShEx-validator/blob/master/tests/updated_hcls.shex

I'm not too sure what is going on with these two repos and where it should actually live. I've added it as a test to the other repo for now.

**Comment by beveradb** [comment]
This issue was moved to HeriotWattMEng2015/ShEx-validator#19
