### ISSUE TITLE
Parsers: Investigate Eric's validation code and figure out how to pull in more parsed data 

### ISSUE THREAD

**Issue by beveradb** [HeriotWattMEng2015/ShExDemo#8]
Modify/ write the JS code to take the parsed Schema and Data and actually perform validation, with useful error messages which are simple enough to help the user. Probably building on top of Eric's work: 
https://github.com/ericprud/ShExDemo/blob/master/demobits/ShExDemo.js

**Comment by tar672** [comment]
@Doix and I are working on it

**Comment by tar672** [comment]
This issue was moved to HeriotWattMEng2015/ShEx-validator#5
